services:
  biblioteca:
    build: .
    container_name: gestor-biblioteca
    restart: unless-stopped
    volumes:
      - /volume1/docker/GestorBiblioteca:/app
      - /app/node_modules
      - "/volume3/BIBLIOTECA DIGITAL/Inbox:/app/Inbox"
      - "/volume3/BIBLIOTECA DIGITAL/CDU:/app/CDU"
      - "/volume3/BIBLIOTECA DIGITAL/Cuarentena:/app/Cuarentena"
      - "/volume3/BIBLIOTECA DIGITAL/Reintentos:/app/Reintentos"
      - "/volume3/BIBLIOTECA DIGITAL/_ER Room:/app/_ER Room"
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
      - PATH_INBOX=/app/Inbox
      - PATH_CDU=/app/CDU
      - PATH_CUARENTENA=/app/Cuarentena
      - PATH_REINTENTOS=/app/Reintentos
      - PATH_ER_ROOM=/app/_ER Room
      - TZ=${TZ:-Europe/Madrid}
      - NODE_OPTIONS=--no-warnings

    working_dir: /app
    command: ["npm", "start"]

